title:              15-418 Final Project
email:              edwardx@andrew.cmu.edu
description:        Parallel Graph Contraction and Minimum Spanning Trees
author:             Edward Xiao & Cole Christini
baseurl:            "/home"
url:                "https://15418.4fecta.ca"

# Social Profiles
twitter_username:   
github_username:    4fecta
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
